# Generated by Django 3.1.1 on 2020-09-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200918_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
