# Generated by Django 3.1.1 on 2020-09-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200918_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='the_comment',
        ),
    ]
